"""test_empty_migration_verification

Revision ID: c4cca0afafbf
Revises: 9c6abaf23451
Create Date: 2025-11-17 18:50:58.919551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4cca0afafbf'
down_revision: Union[str, None] = '9c6abaf23451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
